[package]
name = "comment-commit"
version = "0.1.0"
edition = "2024"

[dependencies]
kenjutu-types = { path = "../kenjutu-types" }
git2 = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
log = "0"
uuid = { version = "1", features = ["v4"] }
fs2 = "0.4.3"

[dev-dependencies]
test-repo = { path = "../test-repo" }
